name: flutter_social_ufollow
version: 0.1.0
publish_to: none
description: See who unfollowed you on social media
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  get: 4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.3.3
  chucker_flutter: ^1.6.0
  get_it: ^7.6.4
  kartal: ^3.4.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

